# Generated by Django 3.2.4 on 2021-07-01 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_garden'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='place_size',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
