# Generated by Django 3.2.5 on 2021-07-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='nick_name',
            new_name='e_mail',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='university',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
    ]
